# Generated by Django 5.1.1 on 2025-02-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('produce', 'Produce'), ('meat', 'Meat'), ('packaged', 'Packaged'), ('fish', 'Fish'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('freezer', 'Freezer')], max_length=255)),
                ('expiration_time', models.DurationField()),
                ('storage', models.CharField(choices=[('refrigerator', 'Refrigerator'), ('pantry', 'Pantry'), ('other', 'Other')], max_length=255)),
            ],
            options={
                'verbose_name': 'Food Category',
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Pantry',
                'verbose_name_plural': 'Pantries',
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=255)),
                ('opened', models.BooleanField(default=False)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchase_location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pantry Item',
                'verbose_name_plural': 'Pantry Items',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upc', models.CharField(max_length=12, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('food_icon', models.ImageField(blank=True, null=True, upload_to='food_icons/')),
                ('department', models.CharField(blank=True, choices=[('produce', 'Produce'), ('meat', 'Meat'), ('packaged', 'Packaged'), ('fish', 'Fish'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('freezer', 'Freezer')], max_length=255, null=True)),
                ('expiration', models.DurationField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.foodcategory')),
            ],
        ),
    ]
