# Generated by Django 5.1.1 on 2025-02-12 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.food'),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='pantry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pantry'),
        ),
        migrations.AddField(
            model_name='pantry',
            name='pantry_items',
            field=models.ManyToManyField(related_name='pantries', to='inventory.pantryitem'),
        ),
    ]
