# Generated by Django 5.1.1 on 2024-11-07 22:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='expiration',
            new_name='expiration_time',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.foodcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='department',
            field=models.CharField(choices=[('produce', 'Produce'), ('meat', 'Meat'), ('packaged', 'Packaged'), ('fish', 'Fish'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('freezer', 'Freezer')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
