# Generated by Django 5.1.1 on 2024-11-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_expiration_foodcategory_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='department',
            field=models.CharField(blank=True, choices=[('produce', 'Produce'), ('meat', 'Meat'), ('packaged', 'Packaged'), ('fish', 'Fish'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('freezer', 'Freezer')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='expiration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
