# Generated by Django 5.1.1 on 2024-11-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_food_department_alter_food_expiration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Categories'},
        ),
        migrations.AlterModelOptions(
            name='pantry',
            options={'verbose_name': 'Pantry', 'verbose_name_plural': 'Pantries'},
        ),
        migrations.RemoveField(
            model_name='pantry',
            name='foods',
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchase_location', models.CharField(max_length=255)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.food')),
                ('pantry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pantry')),
            ],
            options={
                'verbose_name': 'Pantry Item',
                'verbose_name_plural': 'Pantry Items',
            },
        ),
        migrations.AddField(
            model_name='pantry',
            name='pantry_items',
            field=models.ManyToManyField(related_name='pantries', to='inventory.pantryitem'),
        ),
    ]
