# Generated by Django 5.1.1 on 2024-11-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_foodcategory_options_alter_pantry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
