# Generated by Django 5.1.1 on 2025-02-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_pantryitem_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_icon',
            field=models.ImageField(blank=True, null=True, upload_to='food_icons/'),
        ),
        migrations.AddField(
            model_name='food',
            name='upc',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
