# Generated by Django 5.1.1 on 2025-02-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_food_food_icon_food_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dietary_restrictions',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free'), ('nut_free', 'Nut Free'), ('halal', 'Halal'), ('kosher', 'Kosher')], max_length=255),
        ),
    ]
